sudo: required

services:
  - docker
  
before_install:
  - "docker build -t shrini2018/docker-react -f Dockerfile.dev ."
 
script:
  - "docker run -e CI=true shrini2018/docker-react npm run test"

deploy:
    provider: "elasticbeanstalk"
    region: "ap-south-1"
    app: "Docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-934757415082"
    bucket_path: "Docker-react"
    on:
      branch: master
    access_key_id:
      secure: $Access
    secret_access_key:
      secure: "$Secret"
