--- 
before_install: 
  - "docker build -t shrini2018/docker-react -f Dockerfile.dev ."
deploy: 
  - 
    provider: elasticbeanstalk
  - 
    region: ap-south-1
  - 
    app: Docker-react
  - 
    env: DockerReact-env
  - 
    bucket_name: elasticbeanstalk-ap-south-1-934757415082
  - 
    access_key_id: 
      secure: $Access
    bucket_path: Docker-react
    secret_access_key: 
      secure: $Secret
    on: 
      branch: master
language: generic
script: 
  - "docker run -e CI=true shrini2018/docker-react npm run test"
services: 
  - docker
sudo: required
